# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: elkpoc
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
      - 'xpack.license.self_generated.type=trial'
      - 'xpack.security.enabled=false'
      - 'xpack.security.http.ssl.enabled=false'
      - 'xpack.security.transport.ssl.enabled=false'
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -s "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s"'
      interval: 30s
      timeout: 10s
      retries: 5
