# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: elkpoc
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    volumes:
      - ./jenkins/home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:50000:50000
    environment:
      - 'JAVA_OPTS=-Djenkins.install.runSetupWizard=false'
      - 'JENKINS_ADMIN_ID=admin'
      - 'JENKINS_ADMIN_PASSWORD=admin'
