# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: elkpoc
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy