# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: elkpoc
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 9600:9600
    environment:
      - 'LS_JAVA_OPTS=-Xms256m -Xmx256m'
    depends_on:
      elasticsearch:
        condition: service_healthy
