# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: elkpoc
services:
  mysql:
    image: mysql:8.0.30
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=elkPOC
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
